[project]
name = "llm-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "ctranslate2>=4.5.0",
    "granian>=1.7.6",
    "litestar>=2.14.0",
    "msgspec>=0.19.0",
    "picologging>=0.9.3",
    "pydantic-settings>=2.7.1",
    "transformers>=4.48.3",
    "uvloop>=0.21.0",
]

[dependency-groups]
dev = ["nodejs-wheel-binaries>=22.14.0", "pyright>=1.1.394", "ruff>=0.9.6"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "TC", "ANN001", "PLC0414", "INP001", "S104"]

[tool.pyright]
stubPath = "server/typings"
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportPrivateUsage = false
