[project]
name = "llm-api"
version = "0.1.0"
description = "A fast CPU-based API for LLMs"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "ctranslate2>=4.5.0",
    "granian>=1.7.6",
    "jinja2>=3.1.5",
    "litestar>=2.14.0",
    "msgspec>=0.19.0",
    "picologging>=0.9.3",
    "pydantic-settings>=2.7.1",
    "transformers>=4.48.3",
    "uvloop>=0.21.0",
]

[project.scripts]
llm-api = "server:main"

[dependency-groups]
dev = ["nodejs-wheel-binaries>=22.14.0", "pyright>=1.1.394", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["server"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "TC", "ANN001", "PLC0414", "INP001", "S104", "PYI001", "COM812"]

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
stubPath = "server/typings"
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingTypeStubs = false
reportPrivateUsage = false
