name: Build

on:
  push:
    branches: main
    paths:
      - .github/workflows/main.yml
      - .dockerignore
      - Dockerfile.build
      - pyproject.toml
      - uv.lock
      - '**.py'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/uv.yml@main
    with:
      python-version: 3.12
      disable-test: true

  build:
    uses: winstxnhdw/actions/.github/workflows/docker-push.yml@main
    with:
      file: Dockerfile.build
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write

  restart:
    needs: [test, build]
    uses: winstxnhdw/actions/.github/workflows/spaces-restart.yml@main
    secrets:
      token: ${{ secrets.HF_TOKEN }}
